"""Initial migration

Revision ID: 271fa542eb94
Revises: 
Create Date: 2024-11-03 15:10:51.893802

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "271fa542eb94"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "incident_event",
        sa.Column("id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("match_id", sa.Integer(), nullable=True),
        sa.Column("event_id", sa.Integer(), nullable=True),
        sa.Column("minute", sa.Integer(), nullable=True),
        sa.Column("second", sa.Integer(), nullable=True),
        sa.Column("team_id", sa.Integer(), nullable=True),
        sa.Column("player_id", sa.Integer(), nullable=True),
        sa.Column("x", sa.Float(), nullable=True),
        sa.Column("y", sa.Float(), nullable=True),
        sa.Column("expanded_minute", sa.Integer(), nullable=True),
        sa.Column("period_value", sa.Integer(), nullable=True),
        sa.Column("period_display_name", sa.String(), nullable=True),
        sa.Column("type_value", sa.Integer(), nullable=True),
        sa.Column("type_display_name", sa.String(), nullable=True),
        sa.Column("outcome_type_value", sa.Integer(), nullable=True),
        sa.Column("outcome_type_display_name", sa.String(), nullable=True),
        sa.Column("qualifiers", sa.JSON(), nullable=True),
        sa.Column("satisfied_events_types", sa.JSON(), nullable=True),
        sa.Column("is_touch", sa.Boolean(), nullable=True),
        sa.Column("end_x", sa.Float(), nullable=True),
        sa.Column("end_y", sa.Float(), nullable=True),
        sa.Column("goal_mouth_x", sa.Float(), nullable=True),
        sa.Column("goal_mouth_y", sa.Float(), nullable=True),
        sa.Column("related_event_id", sa.Integer(), nullable=True),
        sa.Column("related_player_id", sa.Integer(), nullable=True),
        sa.Column("card_type_value", sa.Integer(), nullable=True),
        sa.Column("card_type_display_name", sa.String(), nullable=True),
        sa.Column("is_goal", sa.Boolean(), nullable=True),
        sa.Column("is_shot", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("incident_event")
    # ### end Alembic commands ###
